spring:
  application:
    name: norush
  data:
    mongodb:
      uri: mydb
      auto-index-creation: true
  security:
    user:
      name: admin
      password: 1234

  profiles:
    include: oauth

jwt:
  secret: qwerasdfzxcvdsafdsaffdasafdfdsafdsafdsafdsasfda
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000

